#!/bin/bash

localrepo=".repo/"
remoterepo="liara:/home/jreese/pub/arch/"
database="noswap.db.tar.xz"

cpuarch=`uname -m`

if [ -z "$1" ]
then
	echo 'Usage: build <package> [... <package>]'
	exit 1
fi

sudo true

echo "Syncing local repository from remote repository..."
rsync -avz --delete $remoterepo $localrepo

cp noswap-repo.sh $localrepo/

archroot=`mktemp --dry-run --tmpdir --directory archroot.XXXXXX`
echo "Creating archroot in $archroot..."

sudo mkarchroot $archroot base base-devel
sudo mkdir -p $archroot/packages/
sudo cp multilib-repo.sh noswap-repo.sh $archroot/packages/
sudo arch-chroot $archroot sh /packages/multilib-repo.sh
sudo arch-chroot $archroot sh /packages/noswap-repo.sh

cleanup() {
	if [ -n "$archroot" ]
	then
		echo "Cleaning up archroot ($archroot) ..."
		sudo rm -rf $archroot*
	fi
}

until [ -z "$1" ]
do
	package=$1
	shift

	if [ -d "$package" ]
	then
		echo
		echo "Starting $package..."

		echo "Checking package type"
		grep arch $package/PKGBUILD | grep -q any
		if [ $? -eq 0 ]
		then
			arch="any"
		else
			arch=$cpuarch
		fi
		echo "Package type: $arch"

		echo "Copying sources to chroot..."
		sudo cp -r $package $archroot/packages/$package

		echo "Building package"
		cmd="cd /packages/${package} && pwd && makepkg --asroot -s --noconfirm"
		echo "chroot# ${cmd}"
		echo $cmd | sudo tee $archroot/packages/run.sh
		sudo arch-chroot $archroot sh /packages/run.sh

		error=$?
		if [ $error -ne 0 ]
		then
			echo "Error building package"
			cleanup
			exit $error
		fi

		echo "Removing old package from repository"
		rm -f ${localrepo}/${package}-?[0-9]*-${arch}.pkg.tar.xz*

		echo "Copying new package to repository"
		cp ${archroot}/packages/${package}/${package}-?[0-9]*-${arch}.pkg.tar.xz $localrepo/

		echo "Entering repository"
		pushd $localrepo

		echo "Signing new package"
		gpg --detach-sign ${package}-?[0-9]*-${arch}.pkg.tar.xz

		echo "Updating database with new package"
		repo-add --sign --verify $database -f ${package}-?[0-9]*-${arch}.pkg.tar.xz

		echo "Leaving repository"
		popd

		echo "Build complete"

		echo "Syncing local repository to remote repository..."
		rsync -avz --delete $localrepo $remoterepo
	fi

	if [ -n "$1" ]
	then
		echo "Updating pacman..."
		sudo arch-chroot $archroot pacman -Sy
	fi
done

cleanup

echo "All package builds completed"
