#!/bin/bash

if [[ $# > 0 ]]; then
	pkg=$1
	echo "Importing PKGBUILD for $pkg from AUR..."
	curl -s https://aur.archlinux.org/packages/${pkg:0:2}/$pkg/$pkg.tar.gz | /bin/tar -xz 2>/dev/null
else
	echo "Updating PKGBUILDs from AUR:"
	for pkg in `ls */PKGBUILD | sed 's@/.*$@@'`; do
		echo $pkg
		curl -s https://aur.archlinux.org/packages/${pkg:0:2}/$pkg/$pkg.tar.gz | /bin/tar -xz 2>/dev/null
	done
fi

echo "Done"
