#!/bin/bash

localrepo=".repo/"
remoterepo="kirby:/home/jreese/pub/arch/"
database="noswap.db.tar.xz"

echo "Syncing local repository from remote repository..."
rsync -avz --delete $remoterepo $localrepo

pushd $localrepo

until [ -z "$1" ]
do
	echo "Removing package $1 from database"
	repo-remove --sign --verify $database $1

	echo "Removing package files from repositry"
	find . -iregex ".*/$1-.?[0-9].*\.pkg\.tar\.xz.*" -delete

	shift
done

popd

echo "Syncing local repository to remote repository..."
rsync -avz --delete $localrepo $remoterepo
