#!/bin/bash

localrepo=".repo/"
remoterepo="kirby:/home/jreese/pub/arch/"
database="noswap.db.tar.xz"

echo "Syncing local repository from remote repository..."
rsync -avz --delete $remoterepo $localrepo

until [ -z "$1" ]
do
    pushd $localrepo

	echo "Removing package $1 from database"
	repo-remove --sign --verify $database $1

	echo "Removing package files from repositry"
	find . -iregex ".*/$1-.?[0-9].*\.pkg\.tar\.xz.*" -delete

    popd

    echo "Removing directory from git and filesystem"
    git rm -rf ./$1
    rm -rf ./$1

	shift
done

echo "Syncing local repository to remote repository..."
rsync -avz --delete $localrepo $remoterepo
