#!/bin/bash

localrepo=".repo/"
remoterepo="kirby:/home/jreese/pub/arch/"
database="noswap.db.tar.xz"

echo "Syncing local repository from remote repository..."
rsync -avz --delete --progress $remoterepo $localrepo

