#!/bin/bash

if [[ $# > 0 ]]; then
	until [ -z "$1" ]
	do
		pkg=$1
		echo "Importing PKGBUILD for $pkg from AUR..."
		curl -s https://aur.archlinux.org/packages/${pkg:0:2}/$pkg/$pkg.tar.gz | /bin/tar -xz 2>/dev/null

		shift
	done

else
	echo "Updating PKGBUILDs from AUR:"
	for pkg in `ls */PKGBUILD | grep -v jreese | sed 's@/.*$@@'`; do
		echo $pkg
		curl -s https://aur.archlinux.org/packages/${pkg:0:2}/$pkg/$pkg.tar.gz | /bin/tar -xz 2>/dev/null &
	done
	wait
fi

echo "Done"
